// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpftygsxopwkshnrcstu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZnR5Z3N4b3B3a3NobnJjc3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzIyMzQsImV4cCI6MjA3MzQ0ODIzNH0.GaxFSw2e4MnbFbjiWepYZSOGN6vWVDXwYzL9ZYNm20w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});